### ISSUE TITLE
ES5 compatible module

### ISSUE THREAD

**Issue by mlshapiro** [usnistgov/jsfive#1]
Hello! Thank you for all the work on this package. We are exciting for a browser only HDF5 reader.

Would you be willing to bundle into an es5 compatible script for use in currently active es5 applications? I understand the push towards the es6 syntax, but I would guess there is still a use case to be able to load this using a simple script tag.

We grabbed your latest and had success making a bundle with [parcel](https://parceljs.org/), but this could be done with any compiler.  Would be great to have this alongside the releases!

**Comment by bmaranville** [comment]
Sure - I would be happy to.  Can you share your parcel bundling setup?

**Comment by bmaranville** [comment]
Ah - I didn't realize how straightforward it is to use parcel.  I have built with parcel and artifacts are commited to the dist/ folder.
