### ISSUE TITLE
Uncaught (in promise) ReferenceError: hdf5 is not defined

### ISSUE THREAD

**Issue by ashishyalameli** [usnistgov/jsfive#2]
I've included the script, but I still am facing this issue. Please help me solve this soon. Thank you.
`<script src="https://cdn.jsdelivr.net/gh/usnistgov/jsfive@master/dist/hdf5.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js"></script>
    <script>
        angular.module('myApp', [])

            .controller("myCtrl", function ($scope, $http) {
                fetch("Link")
                    .then(function (response) {
                        console.log(response);
                        return response.arrayBuffer()
                    })
                    .then(function (buffer) {
                        console.log(buffer);
                        var f = new hdf5.File(buffer, filename);
                        // do something with f;
                        // let g = f.get('group');
                        // let d = f.get('group/dataset');
                        // let v = d.value;
                        // let a = d.attrs;
                        console.log(f);
                    });
            });
    </script>`

**Comment by bmaranville** [comment]
I just fixed this - thanks for finding it.  I hadn't tested the ES2015 script.  Now it defines window.hdf5 for browser use, so you should be able to use your script.
You will have to define or remove 'filename' above, though, since it is currently not defined in your script (but that parameter is optional in the hdf5.File constructor)
By the way - I used the library to look at your datafile, and it works!  I see a single item called "images" in your hdf file, which is a dataset of shape [4, 224, 224, 3] and type uint8

**Comment by ashishyalameli** [comment]
Hi, thanks a lot for solving the issue. But can you please help me out read those images (or image datausri's) to show them in <img> tags.
If you can mail (ashishyalameli@edgetensor.com) me the solution, that would be really helpful.. Thank you.

**Comment by bmaranville** [comment]
Sure - no problem.  After you get f = new hdf5.File(buffer, 'myfilename'); you can get the contents of your images as an array of int by
```
let d = f.get('images');
let imarray = d.value; // this is an array of length 602112 for the file you sent
let shape = d.shape;
let width = shape[1];
let height = shape[2];
// your images are in an inconvenient order... 
// for drawing images it is easiest if the r,g,a,alpha are the fastest-varying element (F-order)
// but for your ordering:
let image_index = 0; //  must be < shape[0] : Bill Gates
let canvas = document.createElement("canvas");
canvas.setAttribute("width", width);
canvas.setAttribute("height", height);
let ctx = canvas.getContext("2d");
let imageData = ctx.createImageData(width, height);
let imageBuffer = imageData.data;
for (var i=0, p=0; i<width; i++) { 
  for (var j=0; j<height; j++) {
    for (var k=0; k<3; k++) {
      imageBuffer[p++] = imarray[k + 3*(j + height*(i + width * image_index))];
    }
    // you don't specify an alpha channel: setting it here:
    imageBuffer[p++] = 255;
  }
}
ctx.putImageData(imageData, 0, 0);

// you can insert this canvas object anywhere you want on your page, e.g. 
// $("#imagediv").append(canvas);
```
