### ISSUE TITLE
Latest changes on master not published on NPM

### ISSUE THREAD

**Issue by MrTeej** [usnistgov/jsfive#28]
Hey, back in December there was a PR: #25 that has been merged into master.

In our project when we install jsfive directly from github master branch, it has the latest changes, it works fine for us after adding the babel plugin in our bundler.

However we noticed that the NPM registry may not be updated with the latest changes.

Thank you!

**Comment by bmaranville** [comment]
I have published [jsfive@0.3.6 on npm](https://www.npmjs.com/package/jsfive/v/0.3.6) with the latest changes.
