### ISSUE TITLE
Version 0.3.8 breaks `npm test` with `create-react-app`

### ISSUE THREAD

**Issue by hubbardp** [usnistgov/jsfive#31]
Using the latest version 0.3.8 in a site created with create-react-app (https://github.com/facebook/create-react-app) works for `npm start` but fails for `npm test`, as shown in this simple example:

1. `$ npx create-react-app test-jsfive`
2. `$ cd test-jsfive`
3. `$ npm install jsfive@0.3.8`
4. Add to `src/App.js`:
    ```
	/* eslint-disable-next-line no-unused-vars */
	import * as hdf5 from 'jsfive';
    ```
5. `$ npm start`
    Works.
6. `$ npm test`
    ```
    SyntaxError: Unexpected token 'export'

      3 |
      4 | /* eslint-disable-next-line no-unused-vars */
    > 5 | import * as hdf5 from 'jsfive';
        | ^
      6 |
      7 | function App() {
      8 |   return (

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/App.js:5:1)
    ```

Reverting to version 0.3.5 and using the older `import` syntax solves the problem:

1. `$ npm uninstall jsfive`
2. `$ npm install jsfive@0.3.5`
3. Change the `import` line in `src/App.js` to:
    ```
	import * as hdf5 from 'jsfive/dist';
    ```
4. `npm start`
    Works.
5. `npm test`
    Works; the one test passes, and the warning that "ReactDOM.render is no longer supported in React 18" seems unrelated.

**Comment by bmaranville** [comment]
This seems to be an error that only occurs with testing, and it seems like this is an error specifically with jest - it is expecting the imports to be CJS unless you make some special notation.  (Apps work just fine).

For the moment, you can indicate to jest that the jsfive import is an ES module, by
<pre><font color="#CC0000">-    &quot;test&quot;: &quot;react-scripts test&quot;,</font>
<font color="#4E9A06">+    &quot;test&quot;: &quot;react-scripts test --transformIgnorePatterns \&quot;node_modules/(?!(jsfive))/\&quot;&quot;,</font>
</pre>

Longer term, I am updating the package.json (see https://github.com/usnistgov/jsfive/commit/64e0927148f3abf9347c2e3703e3850f73038b81) so that the imports are identifiable as CJS and ESM.  This will affect the next release.

**Comment by hubbardp** [comment]
Thanks.  That solution works for the specific problem with Jest, so I will close this issue.

I am still having problems with versions after 0.3.5, though.  Specifically, I have an NPM module, _B_, that imports `jsfive`, and then an application, _A_, created with `create-react-app` that imports _B_ (using `npm link` for development).  I can start _A_ but when it calls code from _B_ it fails:
```
TypeError: hdf5.File is not a constructor
B.js:112 stack: TypeError: hdf5.File is not a constructor
    at FileReader.reader.onload (https://localhost:3000/static/js/main.chunk.js:230:34)
```
I don't need any fancy HDF5 capabilities, so for now, at least, my solution is to just continue using 0.3.5, but I am hoping the problem is solved in the next release, as you mentioned.

**Comment by bmaranville** [comment]
I am having trouble reproducing the issue you describe - I created a dummy package ```jsfive-test``` with an installed jsfive@0.3.8 and this index.js:
```js
import * as hdf5 from 'jsfive';

const DEFAULT_URL = "https://ncnr.nist.gov/pub/ncnrdata/vsans/202009/27864/data/sans66167.nxs.ngv";

export async function load_and_show_keys(file_url = DEFAULT_URL) {
  const result = await fetch(file_url);
  const ab = await result.arrayBuffer();
  const f = new hdf5.File(ab, "file");
  const keys = f.keys;
  console.log(keys);
  return keys;
}
```
And then I did ```npx create-react-app``` in a separate folder, and ```npm link ../../jsfive-test```, and added these lines to the header of src/App.js, and it is able to run and outputs the expected keys for the loaded file when I run ```npm start```
```js
import logo from './logo.svg';
import './App.css';
import  {load_and_show_keys} from 'jsfive-test';

load_and_show_keys();
...
```

Are you building the intermediate library B with webpack or something like that?  I would like to reproduce the problem so I can verify that the new ```package.json``` layout would address it.

**Comment by bmaranville** [comment]
I think in 0.3.6 to 0.3.9 I wasn't creating a CommonJS module, and I think that is what is getting pulled into CRA for some reason (this seems to happen in webpack).

I have added a CommonJS module back into version 0.3.10
