### ISSUE TITLE
v0.3.9 throws TypeError when calling hdf5.File

### ISSUE THREAD

**Issue by FrankNiemeyer** [usnistgov/jsfive#34]
I've recently upgraded to v0.3.9 from v0.3.8. Since then jsfive always gives me a type error when trying to create a new file:

```TypeError: hdf5.File is not a constructor```

That's the code that worked fine until v0.3.9:

```
import * as hdf5 from "jsfive"

export function deserializeRawResultBuffer(arrayBuffer: ArrayBuffer): Result {
    var hdf5File = new hdf5.File(arrayBuffer);
    var results = hdf5File.get('results');
    var scaling = results.attrs.scaling;
    if (scaling && scaling != 1) {
        return new FixedPointResult(new Uint16Array(results.value), scaling);
    } 
    else {
        return new Result(new Float32Array(results.value));
    }    
}
```

**Comment by bmaranville** [comment]
Can you tell me how you are building your project?  E.g. are you using tsc and a bundler of some sort?  I would like to reproduce the error so I can see where it is going wrong.

**Comment by FrankNiemeyer** [comment]
Yes, I'm using webpack (5.72.0) with ts-loader.

`webpack.config.js`:

```
const path = require("path");

module.exports = {
    entry: './src/vtkWrapper.ts',
    mode: 'development',
    resolve: {
        extensions: ['.ts', '.js'],
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: '/node_modules/',
                use: {
                    loader: "babel-loader"
                }
            },
            {
                test: /\.glsl$/,
                use: 'webpack-glsl-loader'
            },
            {
                test: /\.html$/i,
                loader: "html-loader",
            },
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },
        ],        
    },
    output: {
        path: path.resolve(__dirname, '../wwwroot/js'),
        filename: "wrappedVTK.js",
        library: 'VTKWrapper',
    }
};
```

**Comment by bmaranville** [comment]
I am actually very confused by this problem... I am able to reproduce it with your guidance, but I don't understand it.  The package.json section for jsfive related to imports is 
```json
{
  "main": "./dist/hdf5.js",
  "module": "./dist/index.js",
  "exports": {
    ".": {
      "import": "./dist/index.js",
      "require": "./dist/hdf5.js"
    }
  }
}
```
According to all the documentation I can find,  ts-loader will prefer the "module" definition to the "main" definition, and webpack should match the "import" context when loading libraries with an ```import``` statement like you are doing in your code.  But I can clearly see that webpack + ts-loader is grabbing the ```./dist/hdf5.js``` library when it is compiling.

**Comment by bmaranville** [comment]
I think part of the problem is that the CommonJS library was removed when switching over to esbuild (this was an oversight).  It has been re-added at ```dist/cjs/index.js``` in v0.3.10

I think this is still the library that will get pulled in with ```import * as hdf5 from "jsfive";``` which I still don't understand, but at least now it will work!

**Comment by FrankNiemeyer** [comment]
Wow, thanks for the investigation! Really strange, yes. I'll try later whether that fixed my problem.

**Update:** I can confirm that it works fine with v0.3.10. Thanks again!
