### ISSUE TITLE
Range Error with Compressed Files

### ISSUE THREAD

**Issue by anddigital-jh** [usnistgov/jsfive#35]
HI @bmaranville,

You worked very helpfully with my colleague previously regarding ONT's VBZ Compression (https://github.com/usnistgov/jsfive/issues/26).

We noticed an error when working with very large 500MB+ vbz compressed fast5 files.
<img width="741" alt="Screenshot 2022-10-17 at 15 35 32" src="https://user-images.githubusercontent.com/43169343/196205580-a6c72ed2-cf13-4fa8-a899-62985dfd5bc5.png">

It seems that while reading the file, the offset is out of bounds. It essentially jumps from a nominal magnitude of 10^6 to 10^19 which is greater than the byteLength.

The error occurs in the core.js file here:
https://github.com/usnistgov/jsfive/blob/a615913da77a8f46ef0c2b888808884f3b7f8909/esm/core.js#L145

Do you know what could be causing this?

**Comment by bmaranville** [comment]
it is hard for me to guess, without being able to rerun your code and debug it.   
Can you try setting 
```js
var WARN_OVERFLOW = true;
```
on line 162 of core.js?

**Comment by anddigital-jh** [comment]
Thanks for the tip, it was helpful. The getter is a uint8 `getUint8` so it doesn't pass through your DataView64 override methods.

The code is very basic actually. The error is occurring on instantiation. In node for example:

```
import * as hdf5 from 'jsfive';
import fs from "fs";

const filePath = "./file.fast5";
const buffer = fs.readFileSync(filePath, null).buffer;

new hdf5.File(buffer, '');
```

I need to confirm if I can send you over the file due to GDPR or would need to obfuscate it. I will get back to you so you can test on your end.

**Comment by bmaranville** [comment]
I was concerned that the address itself might be overflowing, since that is read as a 64-bit unsigned integer (Q)

Though the max size of an arraybuffer in most browsers is pretty limiting... are you using this in nodejs or a browser?

**Comment by anddigital-jh** [comment]
Yea I was thinking it was overflowing too and I did move from the browser to nodejs, and I'm getting the same error there.

The file is read perfectly fine in all other applications I've tried (your [h5wasm](https://github.com/usnistgov/h5wasm), [ONT's Fast5 API](https://github.com/nanoporetech/ont_fast5_api) and [HD5's official library](https://github.com/HDFGroup/hdf5). That doesn't mean it's not overflowing though as all these other apps don't use native JS DataViews for reading.

**Comment by anddigital-jh** [comment]
I've created a repo with an example where you can reproduce the error. Essentially it's the code I sent above and a link to the large .fast5 file you can download:

https://github.com/anddigital-jh/Large-Fast-5-Test

**Comment by bmaranville** [comment]
Thanks!  I'll give it a shot.

**Comment by bmaranville** [comment]
I found a few problems with the implementation of V2 BTREE, which I fixed.  Your file can at least be instantiated as an hdf5 object. (using the new version v0.3.12 of jsfive).  Let me know if you have further problems.

**Comment by anddigital-jh** [comment]
Thanks a lot for this fix it's been very helpful; I've been able to successfully load the file. The only issue is that when I check the amount of keys / records, I only receive 1 but the file has 4000.

Do you think this is also a problem with the BTREE V2 implementation?

**Comment by bmaranville** [comment]
It might be... can you try loading it with pyfive and see if it works with that?
I can also try myself, since I have the file... can you tell me the path to where you expect to find 4000 keys but only find 1?

EDIT: never mind... I see it.  There is only one key "read_f7ab7a78-f1d2-413f-8a1f-f047165dd675" in the jsfive root object, but there are 4000 keys in the file according to h5py: 
```python
['read_001ae039-6162-465c-a4c3-4a3ad88c2a8a',
 'read_001e1282-987f-49b0-a71a-2c10982f7db0',
 'read_004555ae-8e9b-45d0-b9ed-1b44c275ae0d',
 'read_0045bd12-2784-4e42-a4dc-f82a8d0b43a4',
 'read_004c349f-5eed-441f-9f70-fab9013a1c90',
 'read_005f5ea6-4e9d-4078-8c6f-c856a2246ac9',
 'read_00655b74-c909-4f8c-ad07-8ccbd011ce49',
 'read_006f4916-224d-420b-b762-563c30470977',
 'read_00798268-9efe-4a75-a56d-ba348c1a4caa',
 'read_007c0d8a-05f5-46eb-8ed2-c50263a2c6bd'
 ...]
```

**Comment by bmaranville** [comment]
It looks like handling for the "group info message" (see https://docs.hdfgroup.org/hdf5/develop/_f_m_t3.html#GroupInfoMessage) has not been implemented in pyfive/jsfive.  Only "symbol table message", "link info message", and "link message" have been implemented.  It is failing without error because the function DataOjects.prototype.iter_links ignores messages for which a handler has not been defined.

```js
  * iter_links() {
    for (let msg of this.msgs) {
      if (msg.get('type') == SYMBOL_TABLE_MSG_TYPE) {
        yield* this._iter_links_from_symbol_tables(msg);
      }
      else if (msg.get('type') == LINK_MSG_TYPE) {
        yield this._get_link_from_link_msg(msg);
      }
      else if (msg.get('type') == LINK_INFO_MSG_TYPE) {
        yield* this._iter_link_from_link_info_msg(msg);
      }
    }
  }
```
EDIT: nope - looks like you were right.  There is a problem with the handling of btree v2 link messages when creation order is not specified.

**Comment by bmaranville** [comment]
If I fix the error I found, I get 3416 keys, which is neither 1 nor 4000.  Very confusing.

**Comment by bmaranville** [comment]
Ok, after reverting an earlier minor change I made it is now working - you get 4000 keys.  I haven't published the new version yet, but if you clone this repo and use the most recent version of master it should work for you.

EDIT: see v0.3.13, just published to npm with the fixes.

**Comment by anddigital-jh** [comment]
Thanks. The file loads perfectly now with the correct amount of keys. I've spent the last few days testing multiple types of files and they all work.

Very grateful for your assistance on this yet again!
